version: '3.8'
services:
  shortener:
    build: shortener-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  analytics:
    build: analytics-service
    ports:
      - "8083:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432