basePath: /
definitions:
  handler.shortenRequest:
    properties:
      url:
        type: string
    type: object
  handler.shortenResponse:
    properties:
      short:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple URL shortener service.
  title: Shortener API
  version: "1.0"
paths:
  /{code}:
    get:
      description: Redirect to the original URL by short code
      parameters:
      - description: Short code
        in: path
        name: code
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "302":
          description: Found
        "404":
          description: Not found
          schema:
            type: string
      summary: Expand short code
      tags:
      - shortener
  /shorten:
    post:
      consumes:
      - application/json
      description: Generate a short code for a given URL
      parameters:
      - description: URL to shorten
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.shortenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.shortenResponse'
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Shorten a URL
      tags:
      - shortener
swagger: "2.0"
