package main

import (
	"log"
	"net/http"
	"os"
	"shortener-service/internal/grpcclient"

	"shortener-service/internal/handler"
	"shortener-service/internal/storage"

	"github.com/gorilla/mux"

	httpSwagger "github.com/swaggo/http-swagger"
	_ "shortener-service/docs" // docs is generated by Swag CLI
)

// @title Shortener API
// @version 1.0
// @description This is a simple URL shortener service.
// @host localhost:8080
// @BasePath /
func main() {
	dbHost := os.Getenv("DB_HOST")
	dbPort := os.Getenv("DB_PORT")
	analyticServiceHost := os.Getenv("ANALYTIC_HOST")
	if dbHost == "" {
		dbHost = "localhost"
	}
	if dbPort == "" {
		dbPort = "5432"
	}
	if analyticServiceHost == "" {
		analyticServiceHost = "localhost"
	}
	store, err := storage.NewStorage("postgres://user:password@" + dbHost + ":" + dbPort + "/dbname?sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}

	client, err := grpcclient.NewAnalyticsClient(analyticServiceHost + ":50051") // имя контейнера, если через Docker
	if err != nil {
		log.Fatal(err)
	}

	h := &handler.Handler{
		Storage:         store,
		AnalyticsClient: client,
	}
	r := mux.NewRouter()

	r.HandleFunc("/shorten", h.Shorten).Methods("POST")
	r.HandleFunc("/{code}", h.Expand).Methods("GET")
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	log.Println("Shortener Service started on :8080")
	http.ListenAndServe(":8080", r)
}
